# Generated by Django 4.2.2 on 2023-06-05 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0002_rename_activities_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='remarks',
        ),
        migrations.CreateModel(
            name='Remarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, max_length=300, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='remarks', to='track.activity')),
                ('commenter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='remarks', to='track.member')),
            ],
        ),
    ]
