# Generated by Django 4.2.2 on 2023-06-05 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0003_remove_activity_remarks_remarks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Remarks',
            new_name='Remark',
        ),
    ]
