# Generated by Django 4.2.2 on 2023-06-05 19:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0004_rename_remarks_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='remark',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
